import type { Metadata } from 'next';
import Image from 'next/image';
import Link from 'next/link';
import { notFound } from 'next/navigation';
import HomeGateway from "@/components/HomeGateway";
import DigitalProducts from "@/components/DigitalProducts";
import JapaneseContactForm from '@/components/JapaneseContactForm';
import { industries, services, samples, news } from '@/lib/japanese-content';

const titles:Record<string,string>={'':'必要なものを、確かなかたちで。','trading':'貿易事業','industries':'取扱分野','company':'会社概要','digital-solutions':'デジタルソリューション','consultancy':'市場調査・競合分析','consultancy/samples':'資料サンプル','consultancy/contact':'コンサルティングのご相談','contact':'お問い合わせ','news-room':'ニュース'};
for(const item of industries) titles['industries/'+item.slug]=item.name;
for(const item of news) titles['news-room/'+item.slug]=item.title;
type Props={params:Promise<{path?:string[]}>};
export function generateStaticParams(){return Object.keys(titles).map(path=>({path:path?path.split('/'):[]}));}
export async function generateMetadata({params}:Props):Promise<Metadata>{const path=(await params).path?.join('/')||'';return {title:titles[path]||'ページが見つかりません',description:'株式会社FOCUS。調達・貿易、ビジネスリサーチ、デジタル商品の企画・制作を通じて、事業に必要なものをかたちにします。',alternates:{canonical:'/ja'+(path?'/'+path:''),languages:{en:'/'+path,ja:'/ja'+(path?'/'+path:'')}},openGraph:{locale:'ja_JP',title:titles[path],url:'/ja'+(path?'/'+path:'')}};}
function Button({href='/ja/contact',children='相談する'}:{href?:string;children?:React.ReactNode}){return <Link href={href} className="inline-flex rounded-xl bg-primary px-7 py-3.5 font-semibold text-white transition-colors hover:bg-primary-bright">{children} →</Link>;}
function Hero({title,lead,image}:{title:string;lead:string;image?:string}){return <section className={'relative overflow-hidden px-6 py-16 md:px-12 md:py-32 '+(image?'text-white':'bg-surface-1 text-foreground')}>{image&&<><Image src={image} alt="" fill priority sizes="100vw" className="object-cover"/><div className="absolute inset-0 bg-black/60"/></>}<div className="relative mx-auto max-w-6xl"><p className={'mb-5 text-sm tracking-[.18em] '+(image?'text-white/80':'text-primary')}>株式会社FOCUS</p><h1 className="max-w-4xl text-3xl font-bold md:text-5xl">{title}</h1><p className={'mt-7 max-w-2xl '+(image?'text-white/90':'text-muted')}>{lead}</p></div></section>;}
function Section({title,children,id}:{title?:string;children:React.ReactNode;id?:string}){return <section id={id} className="mx-auto max-w-6xl scroll-mt-28 px-6 py-16 md:px-12">{title&&<h2 className="mb-8 text-2xl font-bold text-foreground md:text-3xl">{title}</h2>}{children}</section>;}
function IndustryCards(){return <div className="grid gap-6 sm:grid-cols-2 lg:grid-cols-3">{industries.map(i=><Link key={i.slug} href={'/ja/industries/'+i.slug} className="group overflow-hidden rounded-2xl border border-primary/15 bg-white"><div className="relative h-48 overflow-hidden"><Image src={'/images/industries/'+i.slug+'.jpg'} alt="" fill sizes="(max-width:640px) 100vw,33vw" className="object-cover transition-transform group-hover:scale-105"/></div><div className="p-6"><h3 className="text-xl font-bold">{i.name} →</h3><p className="mt-3 text-sm text-muted">{i.tagline}</p></div></Link>)}</div>;}
function Downloads(){return <><p className="mb-8 text-muted">以下は英語版の参考資料です。架空の企業・データを用いた説明用サンプルであり、実際のお客様の案件や成果を示すものではありません。</p><div className="grid gap-4 sm:grid-cols-2">{samples.map(([title,file])=><a key={file} href={'/samples/'+encodeURIComponent(file)} className="rounded-xl border border-primary/20 p-6 text-primary hover:bg-surface-1" download><span className="block font-semibold">{title} ↓</span><span className="text-sm">英語版・{file.endsWith('.xlsx')?'Excel':'PDF'}</span></a>)}</div></>;}
export default async function JapanesePage({params}:Props){const path=(await params).path?.join('/')||'';if(!(path in titles))notFound();
const industry=industries.find(i=>path==='industries/'+i.slug);
if(industry)return <main><Hero title={industry.name} lead={industry.tagline} image={'/images/industries/'+industry.slug+'.jpg'}/><Section><div className="grid gap-12 md:grid-cols-2"><div className="space-y-5 text-muted">{industry.description.map(p=><p key={p}>{p}</p>)}</div><div><h2 className="mb-5 text-2xl font-bold">主な取扱品目</h2><ul className="list-disc space-y-3 pl-5 marker:text-primary">{industry.products.map(p=><li key={p}>{p}</li>)}</ul></div></div></Section><Section title="よくあるご質問"><div className="space-y-4">{industry.faqs.map(([q,a])=><details key={q} className="rounded-xl border border-primary/15 bg-surface-1 p-6"><summary className="cursor-pointer font-semibold">{q}</summary><p className="mt-4 text-muted">{a}</p></details>)}</div></Section><Section title="仕様・数量・納期をお聞かせください"><Button/><Link className="ml-6 inline-block py-4 text-primary" href="/ja/industries">取扱分野の一覧へ</Link></Section></main>;
const article=news.find(n=>path==='news-room/'+n.slug);
if(article)return <main><Hero title={article.title} lead={article.date} image={'/images/news/'+article.image}/><Section><article className="max-w-3xl space-y-6 text-muted">{article.body.map(p=><p key={p}>{p}</p>)}</article><Link href="/ja/news-room" className="mt-10 inline-block text-primary">← ニュース一覧へ</Link></Section></main>;
if(path==='')return <HomeGateway japanese/>;
if(path==='digital-solutions')return <main><DigitalProducts japanese/></main>;
if(path==='trading'||path==='industries')return <main><Hero title={path==='trading'?'確かな調達で、事業をつなぐ。':'事業に必要なものを、幅広い分野から。'} lead="自動車、医療機器、文具・消費財、繊維、産業資材。用途と条件を確認し、調達から国際輸送まで支援します。" image="/images/industries/industrial-materials.jpg"/><Section title="取扱分野"><IndustryCards/></Section><Section title="国内外のネットワーク"><p className="max-w-3xl text-muted">大阪を拠点に、ドバイ、カナダ、パキスタンなどの取引先と連携しています。製品仕様、数量、仕向地、希望納期を共有いただき、調達・輸出条件を確認します。</p><div className="mt-8"><Button/></div></Section></main>;
if(path==='company')return <main><Hero title="会社概要" lead="一つひとつの取引と仕事を大切に、継続的な関係を築く。"/><Section><Link href="/ja/news-room" className="font-semibold text-primary">ニュース・お知らせ →</Link></Section><Section title="株式会社FOCUSについて"><div className="max-w-3xl space-y-5 text-muted"><p>株式会社FOCUSは2023年10月に設立され、大阪を拠点に貿易事業を展開しています。国内の製品と海外の買い手をつなぎ、調達・輸出を支援します。</p><p>自動車、医療機器、文具・消費財、繊維、産業資材に加え、ビジネスリサーチやデジタル商品の企画・制作にも取り組んでいます。</p><p>ドバイ、カナダ、パキスタンなどのネットワークを通じて、品質と信頼を大切にした関係づくりを目指します。</p></div></Section><Section title="企業情報"><dl className="divide-y divide-primary/15">{[['会社名','株式会社FOCUS（FOCUS Co., Ltd.）'],['代表取締役','Jamal Ahmad'],['設立','2023年10月'],['資本金','500万円'],['所在地','〒541-0047 大阪府大阪市中央区淡路町3丁目4番1号 212'],['事業内容','貿易・調達、ビジネスリサーチ、コンサルティング、デジタル商品の企画・制作']].map(([k,v])=><div key={k} className="grid gap-2 py-5 sm:grid-cols-[180px_1fr]"><dt className="font-semibold">{k}</dt><dd className="text-muted">{v}</dd></div>)}</dl></Section></main>;
if(path==='contact'||path==='consultancy/contact')return <main><Hero title={titles[path]} lead="ご相談の目的や、必要なものをお聞かせください。最初は短いご説明で大丈夫です。"/><Section><div className="grid gap-12 md:grid-cols-[1.5fr_1fr]"><JapaneseContactForm/><aside className="text-muted"><h2 className="mb-4 text-xl font-bold text-foreground">株式会社FOCUS</h2><p>〒541-0047<br/>大阪府大阪市中央区淡路町3丁目4番1号 212</p><p className="mt-6">営業担当者より24時間以内にご連絡いたします。</p><p className="mt-6">メールでのお問い合わせ</p><a className="break-all text-primary" href="mailto:sales@thefocus.jp">sales@thefocus.jp</a><p className="mt-6 text-sm">フォームに入力いただいた情報は、お問い合わせへの対応に使用します。</p></aside></div></Section></main>;
if(path==='consultancy/samples')return <main><Hero title="成果物のイメージをご確認ください。" lead="構成、情報の整理方法、納品形式をご覧いただくための資料です。"/><Section><Downloads/></Section><Section><Button href="/ja/consultancy/contact"/></Section></main>;
if(path==='news-room')return <main><Hero title="ニュース" lead="FOCUSの取り組みと、事業に関する情報をお届けします。"/><Section><div className="grid gap-6 md:grid-cols-2">{news.map(n=><Link key={n.slug} href={'/ja/news-room/'+n.slug} className="overflow-hidden rounded-2xl border border-primary/15"><div className="relative h-56"><Image src={'/images/news/'+n.image} alt="" fill sizes="(max-width:768px) 100vw,50vw" className="object-cover"/></div><div className="p-6"><p className="mb-3 text-sm text-muted">{n.date}</p><h2 className="text-xl font-bold">{n.title} →</h2></div></Link>)}</div></Section></main>;
return <main><Hero title="市場調査・競合分析" image="/images/news/news-2-dubai.jpg" lead="市場の動向、競合の特徴、事業の可能性。根拠を整理し、次の判断につながる視点を届けます。"/><Section title="リサーチ・事業支援"><div className="grid gap-6 md:grid-cols-2">{services.map(([t,p])=><div key={t} className="rounded-2xl border border-primary/15 p-7"><h3 className="mb-4 text-xl font-bold">{t}</h3><p className="text-muted">{p}</p><div className="mt-6"><Button href="/ja/contact">見積もりを依頼</Button></div></div>)}</div><p className="mt-5 text-sm text-muted">営業担当者より24時間以内にご連絡いたします。</p></Section><Section title="ご相談から納品まで"><ol className="grid gap-6 md:grid-cols-3">{[['01','目的を共有','調べたいこと、想定する利用者、希望納期をお聞かせください。'],['02','範囲と構成を確認','作業範囲、料金、成果物の構成を事前に確認します。'],['03','制作・納品','合意した内容に沿って制作し、納品します。通常のリサーチ案件は3〜7営業日が目安で、修正1回を含みます。']].map(([n,t,p])=><li key={n} className="border-t-2 border-primary pt-5"><span className="text-primary">{n}</span><h3 className="my-3 text-xl font-bold">{t}</h3><p className="text-muted">{p}</p></li>)}</ol></Section><Section title="情報と成果物への姿勢"><ul className="list-disc space-y-4 pl-5 text-muted"><li>数値は出典を示し、推計の場合は前提と算出方法を明記します。</li><li>市場規模の推計は、複数の方法や幅を用いて検討します。</li><li>作業範囲と料金を事前に合意します。</li><li>お客様の非公開情報を、許可なく公開・転用しません。</li></ul></Section><Section id="samples" title="資料サンプル"><Downloads/></Section><Section title="制作会社・支援事業者の皆さまへ"><p className="mb-8 max-w-3xl text-muted">貴社ブランドでの資料制作や、継続的なリサーチ支援にも対応します。納品形式、役割分担、継続案件の条件をご相談ください。</p><Button href="/ja/consultancy/contact"/></Section></main>;
}
